# Generated by Django 3.1.1 on 2020-10-18 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20201018_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 10, 18, 4, 15, 3, 569062, tzinfo=utc)),
        ),
    ]
