# Generated by Django 3.1.1 on 2020-10-18 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20201018_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
