# Generated by Django 3.1.1 on 2020-11-03 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20201018_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealedBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateField(default=django.utils.timezone.now)),
                ('min_bid', models.IntegerField()),
                ('auction_id', models.CharField(max_length=30)),
                ('item_description', models.CharField(max_length=400)),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.profile')),
            ],
        ),
    ]
