# Generated by Django 3.1.1 on 2020-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_sealedbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealedbid',
            name='auction_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sealedbid',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
