# Generated by Django 3.1.1 on 2020-12-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20201106_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.CharField(max_length=50),
        ),
    ]
