# Generated by Django 3.1.1 on 2021-02-12 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=400)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('auction_id', models.CharField(blank=True, max_length=30)),
                ('min_bid', models.IntegerField()),
                ('start_price', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
