# Generated by Django 3.1.1 on 2021-03-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_channel_sqeuze'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sqeuze',
            new_name='Squeeze',
        ),
    ]
