jobs:
  include:
    - language: python
      python: "3.8"
      install:
        - pip install -r requirements.txt
        - wget https://github.com/ethereum/solidity/releases/download/v0.7.5/solc-static-linux
        - mv solc-static-linux solc
        - chmod +x solc
        - export PATH=$PATH:$(pwd)
      script:
        - cd bca_django 
        - flake8 --ignore=E501,F401
        - python manage.py test

    - language: node_js
      node_js: 
        - 14
      install: 
        - cd bca_react && npm install
      script:
        - npm run build
        - npm run test
        - npm run test-sol
